
package au.edu.unsw.soacourse.marketservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-04-15T15:23:00.484+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "convertMarketFault", targetNamespace = "http://marketservice.soacourse.unsw.edu.au")
public class ConvertMarketDataFaultMsg extends Exception {
    
    private au.edu.unsw.soacourse.marketservice.ServiceFaultType convertMarketFault;

    public ConvertMarketDataFaultMsg() {
        super();
    }
    
    public ConvertMarketDataFaultMsg(String message) {
        super(message);
    }
    
    public ConvertMarketDataFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public ConvertMarketDataFaultMsg(String message, au.edu.unsw.soacourse.marketservice.ServiceFaultType convertMarketFault) {
        super(message);
        this.convertMarketFault = convertMarketFault;
    }

    public ConvertMarketDataFaultMsg(String message, au.edu.unsw.soacourse.marketservice.ServiceFaultType convertMarketFault, Throwable cause) {
        super(message, cause);
        this.convertMarketFault = convertMarketFault;
    }

    public au.edu.unsw.soacourse.marketservice.ServiceFaultType getFaultInfo() {
        return this.convertMarketFault;
    }
}
