
package au.edu.unsw.soacourse.marketservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-04-15T15:23:00.529+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "showMarketDataFault", targetNamespace = "http://marketservice.soacourse.unsw.edu.au")
public class ShowMarketDataFaultMsg extends Exception {
    
    private au.edu.unsw.soacourse.marketservice.ServiceFaultType showMarketDataFault;

    public ShowMarketDataFaultMsg() {
        super();
    }
    
    public ShowMarketDataFaultMsg(String message) {
        super(message);
    }
    
    public ShowMarketDataFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public ShowMarketDataFaultMsg(String message, au.edu.unsw.soacourse.marketservice.ServiceFaultType showMarketDataFault) {
        super(message);
        this.showMarketDataFault = showMarketDataFault;
    }

    public ShowMarketDataFaultMsg(String message, au.edu.unsw.soacourse.marketservice.ServiceFaultType showMarketDataFault, Throwable cause) {
        super(message, cause);
        this.showMarketDataFault = showMarketDataFault;
    }

    public au.edu.unsw.soacourse.marketservice.ServiceFaultType getFaultInfo() {
        return this.showMarketDataFault;
    }
}
